from enum import Enum

class STATUS(Enum):
    NOT_INITIALIZED = 0
    CREATED = 1
    MESSAGE_SENT = 2
    MESSAGE_RECEIVED = 3
    PROCESSING = 4
    DONE = 9

    # >= 50 e < 60 : Falha no processo (realizar nova tentiva)
    ERROR_FAILED_TO_CONNECT_TO_BASE_OR_SERVICE = 50
    ERROR_FAILED_TO_SEND_MESSAGE = 51
    ERROR_RESPONSE_RETURNED_WITH_ERROR = 52
    ERROR_RESPONSE_SLA_EXPIRED = 53
    ERROR_RESPONSE_PROCESSING_FAILED = 54
    ERROR_EXPIRED_PROCESSING_SLA = 55
    ERROR_GENERIC_FAILURE = 58
    ERROR_UNAUTHORIZED = 59

    # > 90 : Processo encerrado com erro terminal

    FATAL_ERROR_ATTEMPTS_EXHAUSTED = 98
    FATAL_ERROR_UNAUTHORIZED = 99
