# services:
#   rabbitmq:
#     image: rabbitmq:3-management-alpine
#     container_name: 'rabbitmq'
#     ports:
#         - 5672:5672
#         - 15672:15672
#     volumes:
#         - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#         - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#     networks:
#         - rabbitmq_go_net

# networks:
#   rabbitmq_go_net:
#     driver: bridge

services:
        rabbitmq:
               image: rabbitmq:4.0.2-management
               container_name: rabbitmq_management
               ports: 
                - 5672:5672
                - 25672:25672 # (erlang) communication between the nodes and CLI tool
                - 15672:15672 # communication with the web management API 
               volumes:
                - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
                - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
               restart: always
               networks:
                - rabbitmq_net
networks:
    rabbitmq_net:
        driver: bridge

# volumes:
#     logs-folder:
#         name: ${log_rabbitmq_management}
#         driver: local